In [42]:
import pandas as pd
bike_df = pd.read_csv('data/citibike-tripdata.csv', sep=',')
display(bike_df)

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1
1,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,3242.0,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0
2,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1
3,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,308.0,St James Pl & Oliver St,40.713079,-73.998512,3690.0,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2
4,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,345.0,W 13 St & 6 Ave,40.736494,-73.997044,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,2018-09-05 19:08:27.8460,2018-09-05 19:15:51.4940,494.0,W 26 St & 8 Ave,40.747348,-73.997236,448.0,W 37 St & 10 Ave,40.756604,-73.997901,19531,Subscriber,1990,2
299996,2018-09-05 19:08:28.3700,2018-09-05 19:20:01.5080,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,3086.0,Graham Ave & Conselyea St,40.715143,-73.944507,34020,Subscriber,1982,1
299997,2018-09-05 19:08:27.5090,2018-09-05 19:13:40.5060,3686.0,Gansevoort St & Hudson St,40.739448,-74.005070,168.0,W 18 St & 6 Ave,40.739713,-73.994564,33220,Subscriber,1991,1
299998,2018-09-05 19:08:29.2300,2018-09-05 20:04:29.3220,254.0,W 11 St & 6 Ave,40.735324,-73.998004,499.0,Broadway & W 60 St,40.769155,-73.981918,34744,Subscriber,1975,0
299999,2018-09-05 19:08:29.7110,2018-09-05 19:12:14.7620,3496.0,1 Ave & E 110 St,40.792327,-73.938300,3502.0,Lexington Ave & E 111 St,40.795412,-73.944123,18292,Subscriber,1966,1

In [43]:
bike_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  object
 1   stoptime                 300000 non-null  object
 2   start station id         299831 non-null  float64
 3   start station name       299831 non-null  object
 4   start station latitude   300000 non-null  float64
 5   start station longitude  300000 non-null  float64
 6   end station id           299831 non-null  float64
 7   end station name         299831 non-null  object
 8   end station latitude     300000 non-null  float64
 9   end station longitude    300000 non-null  float64
 10  bikeid                   300000 non-null  int64
 11  usertype                 300000 non-null  object
 12  birth year               300000 non-null  int64
 13  gender                   300000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 32.0+ MB

In [44]:
bike_df['start station id'].mode()

0    281.0
Name: start station id, dtype: float64

In [45]:
bike_df['bikeid'].mode()

0    33887
Name: bikeid, dtype: int64

In [46]:
display(round(bike_df['usertype'].value_counts(normalize=True), 2))

usertype
Subscriber    0.77
Customer      0.23
Name: proportion, dtype: float64

In [47]:
display(bike_df[bike_df['gender'] == 1].shape[0])
display(bike_df[bike_df['gender'] == 2].shape[0])

183582

74506

In [48]:
bike_df.describe(include=['object'])

,starttime,stoptime,start station name,end station name,usertype
count,300000,300000,299831,299831,300000
unique,299836,299813,759,765,2
top,2018-09-02 13:59:41.7770,2018-09-04 17:51:07.9110,Grand Army Plaza & Central Park S,West St & Chambers St,Subscriber
freq,2,2,1928,1963,232202

In [49]:
bike_df['start station name'].value_counts()

start station name
Grand Army Plaza & Central Park S    1928
Central Park S & 6 Ave               1909
Pershing Square North                1873
12 Ave & W 40 St                     1845
West St & Chambers St                1835
                                     ...
NYCBS Depot - GOW                      15
Franklin Ave & Empire Blvd             11
Railroad Ave & Kay Ave                  9
47 Ave & Skillman Ave                   7
Eastern Pkwy & Washington Ave           6
Name: count, Length: 759, dtype: int64

In [50]:
bike_df.drop(['start station id', 'end station id'], axis=1, inplace=True)
display(bike_df)

,starttime,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,MacDougal St & Washington Sq,40.732264,-73.998522,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1
1,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,Cadman Plaza West & Montague St,40.693830,-73.990539,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0
2,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,1 Ave & E 62 St,40.761227,-73.960940,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1
3,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,St James Pl & Oliver St,40.713079,-73.998512,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2
4,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,W 13 St & 6 Ave,40.736494,-73.997044,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1
...,...,...,...,...,...,...,...,...,...,...,...,...
299995,2018-09-05 19:08:27.8460,2018-09-05 19:15:51.4940,W 26 St & 8 Ave,40.747348,-73.997236,W 37 St & 10 Ave,40.756604,-73.997901,19531,Subscriber,1990,2
299996,2018-09-05 19:08:28.3700,2018-09-05 19:20:01.5080,Kent Ave & N 7 St,40.720368,-73.961651,Graham Ave & Conselyea St,40.715143,-73.944507,34020,Subscriber,1982,1
299997,2018-09-05 19:08:27.5090,2018-09-05 19:13:40.5060,Gansevoort St & Hudson St,40.739448,-74.005070,W 18 St & 6 Ave,40.739713,-73.994564,33220,Subscriber,1991,1
299998,2018-09-05 19:08:29.2300,2018-09-05 20:04:29.3220,W 11 St & 6 Ave,40.735324,-73.998004,Broadway & W 60 St,40.769155,-73.981918,34744,Subscriber,1975,0
299999,2018-09-05 19:08:29.7110,2018-09-05 19:12:14.7620,1 Ave & E 110 St,40.792327,-73.938300,Lexington Ave & E 111 St,40.795412,-73.944123,18292,Subscriber,1966,1

In [51]:
bike_df['age'] = 2018-bike_df['birth year']
bike_df.drop(['birth year'], axis=1, inplace=True)
display(bike_df[bike_df['age'] > 60])

,starttime,stoptime,start station name,start station latitude,start station longitude,end station name,end station latitude,end station longitude,bikeid,usertype,gender,age
53,2018-09-01 00:04:20.9200,2018-09-01 00:11:21.6180,Grand Army Plaza & Central Park S,40.764397,-73.973715,Broadway & W 53 St,40.763441,-73.982681,24824,Subscriber,2,63
373,2018-09-01 00:25:47.6740,2018-09-01 00:39:31.7160,Mott St & Prince St,40.723180,-73.994800,Mott St & Prince St,40.723180,-73.994800,26083,Subscriber,2,68
405,2018-09-01 00:29:10.1630,2018-09-01 00:44:08.6110,Avenue D & E 3 St,40.720828,-73.977932,Avenue D & E 12 St,40.725806,-73.974225,33436,Subscriber,2,61
435,2018-09-01 00:31:21.7250,2018-09-01 00:41:57.9200,Broadway & W 56 St,40.765265,-73.981923,W 37 St & 10 Ave,40.756604,-73.997901,19894,Subscriber,2,63
457,2018-09-01 00:33:19.8080,2018-09-01 00:37:29.9270,Warren St & Court St,40.686371,-73.993833,Bond St & Bergen St,40.684967,-73.986208,34173,Subscriber,1,118
...,...,...,...,...,...,...,...,...,...,...,...,...
299882,2018-09-05 19:07:25.4010,2018-09-05 19:35:36.5000,Amsterdam Ave & W 66 St,40.774667,-73.984706,Cathedral Pkwy & Broadway,40.804213,-73.966991,16376,Subscriber,1,64
299883,2018-09-05 19:07:24.9130,2018-09-05 19:20:20.2760,W 4 St & 7 Ave S,40.734011,-74.002939,E 2 St & Avenue A,40.723077,-73.985836,29943,Subscriber,2,70
299946,2018-09-05 19:08:06.4620,2018-09-05 19:20:16.0180,Henry St & Grand St,40.714215,-73.981346,Lafayette St & E 8 St,40.730207,-73.991026,30951,Subscriber,1,71
299957,2018-09-05 19:08:12.5770,2018-09-05 19:42:24.0340,Market St & Cherry St,40.710762,-73.994004,Catherine St & Monroe St,40.711174,-73.996826,31453,Subscriber,1,76
299990,2018-09-05 19:08:26.2640,2018-09-05 19:44:53.7800,Columbus Ave & W 72 St,40.777057,-73.978985,Hudson St & Reade St,40.716250,-74.009106,26377,Subscriber,1,66

In [52]:
bike_df['starttime'] = pd.to_datetime(bike_df['starttime'])
bike_df['stoptime'] = pd.to_datetime(bike_df['stoptime'])
bike_df['trip duration'] = bike_df['stoptime']-bike_df['starttime']
display(bike_df.loc[3, 'trip duration'])

Timedelta('0 days 00:07:16.837000')

In [53]:
weekday = bike_df['starttime'].dt.dayofweek
bike_df['weekend'] = weekday.apply(lambda x: 1 if x==5 or x==6 else 0)
bike_df['weekend'].sum()

115135

In [57]:
def get_time_of_day(time):
    if 0 <= time <= 6:
        return 'night'
    if 6 < time <= 12:
        return 'morning'
    if 12 < time <= 18:
        return 'day'
    return 'evening'

hour = bike_df['starttime'].dt.hour
bike_df['time of day'] = hour.apply(get_time_of_day)

day_rides = bike_df[bike_df['time of day'] == 'day'].shape[0]
night_rides = bike_df[bike_df['time of day'] == 'night'].shape[0]
display(round(day_rides/night_rides))

9