In [1]:
import pandas as pd

movies_df = pd.read_csv('data/ratings_movies.csv')
display(movies_df)

,Unnamed: 0,userId,movieId,rating,date,title,genres
0,0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...,...
100831,100831,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller
100832,100832,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,100833,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror
100834,100834,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi
100835,100835,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller

In [3]:
#библиотека для регулярных выражений
import re 
def get_year_release(arg):
    #находим все слова по шаблону "(DDDD)"
    candidates = re.findall(r'\(\d{4}\)', arg) 
    # проверяем число вхождений
    if len(candidates) > 0:
        #если число вхождений больше 0,
	#очищаем строку от знаков "(" и ")"
        year = candidates[0].replace('(', '')
        year = year.replace(')', '')
        return int(year)
    else:
        #если год не указан, возвращаем None
        return None

In [4]:
movies_df['year_release'] = movies_df['title'].apply(get_year_release).astype('Int32')
display(movies_df)

,Unnamed: 0,userId,movieId,rating,date,title,genres,year_release
0,0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,1995
2,2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,1995
3,3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995
4,4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995
...,...,...,...,...,...,...,...,...
100831,100831,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller,2017
100832,100832,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller,2017
100833,100833,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror,2017
100834,100834,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi,2017
100835,100835,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,2017

In [5]:
movies_df['year_release'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 100836 entries, 0 to 100835
Series name: year_release
Non-Null Count   Dtype
--------------   -----
100818 non-null  Int32
dtypes: Int32(1)
memory usage: 492.5 KB

In [6]:
movies_df[movies_df['year_release'] == 1999].groupby('title')['rating'].agg(['mean', 'min']).sort_values(by=['mean', 'min'], ascending=[True, True])

                                                  mean  min
title
Bloodsport: The Dark Kumite (1999)                 0.5  0.5
Chill Factor (1999)                                1.0  1.0
From Dusk Till Dawn 2: Texas Blood Money (1999)    1.0  1.0
Julien Donkey-Boy (1999)                           1.0  1.0
Simon Sez (1999)                                   1.0  1.0
...                                                ...  ...
Mickey's Once Upon a Christmas (1999)              5.0  5.0
On the Ropes (1999)                                5.0  5.0
Siam Sunset (1999)                                 5.0  5.0
Sun Alley (Sonnenallee) (1999)                     5.0  5.0
Trailer Park Boys (1999)                           5.0  5.0

[261 rows x 2 columns]

In [7]:
movies_df[movies_df['year_release'] == 2010].groupby('genres')['rating'].agg(['mean', 'min']).sort_values(by=['mean', 'min'], ascending=[True, True])

                                       mean  min
genres
Action|Sci-Fi                      1.000000  1.0
Action|Adventure|Horror            1.500000  1.5
Action|Drama|Fantasy               1.500000  1.5
Crime|Romance                      1.500000  1.5
Adventure|Comedy|Fantasy           1.833333  0.5
...                                     ...  ...
Sci-Fi                             4.750000  4.5
Adventure|Children|Comedy|Mystery  5.000000  5.0
Animation|Children|Mystery         5.000000  5.0
Animation|Drama|Fantasy|Mystery    5.000000  5.0
Comedy|Musical                     5.000000  5.0

[119 rows x 2 columns]

In [9]:
movies_df.groupby('userId')['genres'].agg(
    ['nunique', set]
).sort_values(by='nunique', ascending=False)

        nunique                                                set
userId
599         524  {Action|Adventure|Sci-Fi, Action|Adventure|Dra...
414         482  {Musical|Romance, Action|Adventure|Sci-Fi, Act...
448         403  {Action|Animation|Mystery|IMAX, Musical|Romanc...
380         399  {Action|Animation|Mystery|IMAX, Musical|Romanc...
474         395  {Adventure|Animation|Children|Drama|Musical, M...
...         ...                                                ...
578          15  {Drama|Romance, Adventure|Drama|Thriller, Dram...
12           15  {Action|Drama|Romance, Drama|Romance, Comedy|F...
85           13  {Drama|Romance, Drama, Adventure|Drama, Drama|...
214          13  {Drama|Romance, Drama, Comedy|Fantasy|Romance|...
245          13  {Crime|Drama, Drama|Romance, Drama, Animation|...

[610 rows x 2 columns]

In [10]:
movies_df.groupby('userId')['rating'].agg(
    ['nunique', 'mean']
).sort_values(by='mean', ascending=False)

        nunique      mean
userId
53            1  5.000000
251           3  4.869565
515           3  4.846154
25            3  4.807692
30            4  4.735294
...         ...       ...
567          10  2.245455
153          10  2.217877
508           6  2.145833
139           8  2.144330
442           5  1.275000

[610 rows x 2 columns]

In [12]:
mask = movies_df['year_release'] == 2018
grouped = movies_df[mask].groupby('genres')['rating'].agg(
    ['mean', 'count']
)
grouped[grouped['count'] > 10].sort_values(by='mean', ascending=False)

                             mean  count
genres
Action|Adventure|Sci-Fi  3.928571     14
Action|Comedy|Sci-Fi     3.875000     12

In [34]:
movies_df['date'] = pd.to_datetime(movies_df['date'])
movies_df['year_rating'] = movies_df['date'].dt.year

pivot = movies_df.pivot_table(
    values='rating',
    index='year_rating',
    columns='genres',
    aggfunc='mean'
)

pd.set_option('display.max_rows', None)
display(pivot.loc[2018].sort_values(ascending=False))

genres
Animation|Comedy|Drama                                                           5.000000
Crime|Mystery                                                                    5.000000
Comedy|Crime|Fantasy                                                             5.000000
Crime|Fantasy|Horror                                                             5.000000
Comedy|Crime|Horror|Thriller                                                     5.000000
Animation|Crime|Drama                                                            5.000000
Drama|Romance|War                                                                5.000000
Action|Comedy|Documentary                                                        5.000000
Animation|Comedy|Fantasy|Musical                                                 5.000000
Animation|Comedy|Drama|Fantasy|Sci-Fi                                            5.000000
Comedy|Drama|Fantasy|Mystery|Romance                                             5.000000
Animation|Children|Mystery                                                       5.000000
Drama|Horror|Mystery|Sci-Fi|Thriller                                             5.000000
Adventure|Children|Comedy|Fantasy|Mystery                                        5.000000
Comedy|Fantasy|Horror|Musical|Thriller                                           5.000000
Romance|Sci-Fi                                                                   5.000000
Mystery|Romance|Sci-Fi|Thriller                                                  5.000000
Adventure|Fantasy|Musical                                                        5.000000
Action|Crime|Thriller|Western                                                    5.000000
Action|Crime|Sci-Fi|Thriller                                                     5.000000
Comedy|Horror|Mystery                                                            5.000000
Drama|Fantasy|Romance|Sci-Fi                                                     4.750000
Comedy|Drama|Mystery                                                             4.750000
Comedy|Drama|Horror                                                              4.750000
Action|Adventure|War                                                             4.500000
Adventure|Animation|Fantasy|Romance                                              4.500000
Comedy|Romance|Thriller                                                          4.500000
Adventure|Animation|Romance                                                      4.500000
Action|Adventure|Mystery|Romance|Thriller                                        4.500000
Action|Adventure|Comedy|Drama|Fantasy|Thriller                                   4.500000
Action|Adventure|Comedy|Fantasy|Sci-Fi|Thriller                                  4.500000
Adventure|Animation|Children|Romance|Sci-Fi                                      4.500000
Adventure|Animation|Children|Drama|Musical                                       4.500000
Comedy|Documentary|Romance                                                       4.500000
Children|Comedy|Sci-Fi                                                           4.500000
Crime|Drama|Film-Noir|Thriller                                                   4.500000
Adventure|Comedy|Horror|Romance                                                  4.500000
Adventure|Film-Noir|Sci-Fi|Thriller                                              4.500000
Adventure|Thriller                                                               4.500000
Drama|Mystery|Sci-Fi                                                             4.500000
Film-Noir|Mystery|Thriller                                                       4.500000
Animation|Romance                                                                4.500000
Action|Comedy|Fantasy|Sci-Fi                                                     4.500000
Animation|Comedy|Sci-Fi                                                          4.357143
Action|Adventure|Comedy|Crime|Mystery|Thriller                                   4.300000
Action|Drama|Romance                                                             4.300000
Animation|Children|Comedy|Fantasy                                                4.300000
Drama|Western                                                                    4.285714
Comedy|Crime|Drama|Thriller                                                      4.260870
Animation|Fantasy|Thriller                                                       4.250000
Comedy|Crime|Mystery|Thriller                                                    4.250000
Action|Drama|Mystery|Sci-Fi|Thriller|IMAX                                        4.250000
Action|Animation|Drama|Fantasy|Sci-Fi                                            4.250000
Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX                                  4.250000
Action|Adventure|Horror|Sci-Fi                                                   4.250000
Action|Crime|Drama|Western                                                       4.250000
Children|Drama|Sci-Fi                                                            4.250000
Crime                                                                            4.250000
Adventure|Children|Fantasy|Musical                                               4.250000
Children|Drama|Fantasy|Romance                                                   4.250000
Action|Horror|Sci-Fi|IMAX                                                        4.250000
Adventure|Children|Comedy|Mystery                                                4.250000
Documentary|War                                                                  4.250000
Action|Crime|Drama|IMAX                                                          4.233333
Animation                                                                        4.204545
Adventure|Animation|Children|Drama                                               4.200000
Animation|Sci-Fi                                                                 4.166667
Action|Adventure|Animation|Children|Comedy|Western                               4.166667
Comedy|Drama|Romance|War                                                         4.160000
Drama|Thriller|War                                                               4.153846
Action|Adventure|Animation|Children|Comedy|Fantasy                               4.142857
Adventure|Fantasy|Thriller|IMAX                                                  4.125000
Animation|Comedy|Fantasy                                                         4.125000
Action|Crime|Drama|Mystery|Thriller                                              4.111111
Action|Adventure|Crime|Drama|Thriller                                            4.100000
Action|Adventure|Western                                                         4.100000
Action|Adventure|Drama|Fantasy|Mystery|IMAX                                      4.100000
Adventure|Animation|Fantasy                                                      4.100000
Action|Drama|War                                                                 4.060976
Action|Adventure|Drama                                                           4.057692
Adventure|Fantasy|Mystery|Romance|IMAX                                           4.055556
Drama|Romance|Sci-Fi                                                             4.045455
Animation|Children|Drama                                                         4.035714
Children|Comedy|Drama|Mystery                                                    4.000000
Action|Animation|Sci-Fi|Thriller                                                 4.000000
Adventure|Children|Comedy|Drama|Fantasy|Sci-Fi                                   4.000000
Drama|Horror|Sci-Fi|Thriller                                                     4.000000
Action|Animation|Fantasy|IMAX                                                    4.000000
Animation|Fantasy|Horror|Mystery                                                 4.000000
Action|Animation|Mystery                                                         4.000000
Action|Comedy|Crime|Fantasy                                                      4.000000
Action|Sci-Fi|Thriller|Western                                                   4.000000
Action|Comedy|Crime|Horror                                                       4.000000
Action|Comedy|Crime|Mystery                                                      4.000000
Animation|Drama|Fantasy|Romance                                                  4.000000
Action|Adventure|Comedy|Fantasy|Horror                                           4.000000
Adventure|Animation|Children|Comedy|Fantasy|Musical|Romance                      4.000000
Action|Adventure|Animation|Sci-Fi|Thriller                                       4.000000
Action|Comedy|Fantasy|Horror                                                     4.000000
Action|Adventure|Animation|Fantasy                                               4.000000
Fantasy|Horror|Mystery|Romance                                                   4.000000
Fantasy|Sci-Fi                                                                   4.000000
Action|Comedy|Horror|Thriller                                                    4.000000
Action|Comedy|IMAX                                                               4.000000
Action|Comedy|Musical                                                            4.000000
Film-Noir|Mystery                                                                4.000000
Adventure|Children|Drama|Sci-Fi                                                  4.000000
Drama|Fantasy|Thriller                                                           4.000000
Crime|Drama|Horror|Thriller                                                      4.000000
Adventure|Children|Comedy|Fantasy|Sci-Fi                                         4.000000
Crime|Film-Noir|Thriller                                                         4.000000
Mystery|Thriller                                                                 4.000000
Crime|Documentary                                                                4.000000
Comedy|Sci-Fi|War                                                                4.000000
Adventure|Animation|Comedy|Sci-Fi                                                4.000000
Adventure|Comedy|Musical|Sci-Fi                                                  4.000000
Adventure|Animation|Drama|Horror                                                 4.000000
Adventure|Drama|Fantasy|IMAX                                                     4.000000
Action|Mystery|Sci-Fi|Thriller                                                   4.000000
Comedy|Drama|Fantasy|Romance|Thriller                                            4.000000
Adventure|Drama|Thriller|IMAX                                                    4.000000
Crime|Drama|Romance|Thriller                                                     4.000000
Action|Crime|Horror|Sci-Fi|Thriller                                              4.000000
Action|Adventure|Animation|Children|Comedy|Sci-Fi                                4.000000
Mystery                                                                          4.000000
Action|Animation|Comedy|Fantasy                                                  4.000000
Action|Adventure|Comedy|Fantasy|Romance                                          4.000000
Action|Drama|Romance|Sci-Fi                                                      4.000000
Action|Crime|Drama|Thriller                                                      4.000000
Drama|Fantasy|Musical|Romance                                                    4.000000
Adventure|Fantasy|IMAX                                                           3.946429
Adventure|Children|Comedy|Fantasy                                                3.944444
Adventure|Animation|Children|Comedy|Musical                                      3.928571
Action|Adventure|Children|Sci-Fi                                                 3.900000
Action|Drama|Western                                                             3.900000
Adventure|Sci-Fi|Thriller                                                        3.900000
Crime|Horror                                                                     3.900000
Adventure|Fantasy                                                                3.898148
Adventure|Animation|Children|Comedy|Fantasy|IMAX                                 3.888889
Drama|Fantasy|Mystery|Romance                                                    3.888889
Adventure|Animation|Children|Fantasy|IMAX                                        3.882353
Comedy|Horror|Thriller                                                           3.875000
Drama|Mystery|Sci-Fi|Thriller                                                    3.850000
Action|Adventure|Crime|IMAX                                                      3.846154
Crime|Horror|Thriller                                                            3.846154
Adventure|Mystery|Sci-Fi|Thriller                                                3.833333
Adventure|Comedy|Drama                                                           3.833333
Action|Adventure|Animation|Comedy                                                3.833333
Animation|Fantasy|Mystery                                                        3.833333
Animation|Children|Drama|Fantasy                                                 3.833333
Comedy|Crime|Drama|Romance                                                       3.833333
Action|Adventure|Comedy|Thriller                                                 3.833333
Crime|Drama                                                                      3.826613
Adventure|Animation|Children                                                     3.805556
Animation|Children|Fantasy|Musical                                               3.800000
Documentary                                                                      3.777174
Adventure|Drama|Sci-Fi                                                           3.775000
Adventure|Drama|Fantasy|Sci-Fi                                                   3.750000
Action|Crime|IMAX                                                                3.750000
Action|Comedy|Fantasy|IMAX                                                       3.750000
Comedy|Western                                                                   3.750000
Action|Adventure|Crime|Horror|Thriller                                           3.750000
Comedy|Crime|Drama|Romance|Thriller                                              3.750000
Action|Adventure|Drama|Fantasy|Thriller                                          3.750000
Comedy|Crime|Mystery                                                             3.750000
Adventure|Animation|Children|Drama|Sci-Fi                                        3.750000
Action|Animation|Drama|Sci-Fi                                                    3.750000
Action|Adventure|Animation|Children|Comedy                                       3.741935
Crime|Drama|Mystery|Thriller                                                     3.733333
Action|Animation|Comedy                                                          3.730769
Drama|Horror|Mystery                                                             3.727273
Adventure|Drama                                                                  3.722222
Crime|Mystery|Thriller                                                           3.716667
Crime|Drama|Thriller                                                             3.712500
Animation|Comedy|Fantasy|Musical|Romance                                         3.700000
Animation|Drama|Romance                                                          3.700000
Adventure|Drama|War                                                              3.700000
Crime|Film-Noir|Mystery|Thriller                                                 3.700000
Action|Adventure|Animation|Children|Comedy|IMAX                                  3.700000
Comedy|Drama|Sci-Fi                                                              3.692308
Action|Crime|Thriller                                                            3.688679
Action|Crime|Mystery|Thriller                                                    3.681818
(no genres listed)                                                               3.676471
Drama|Mystery|Thriller                                                           3.674419
Action|Crime|Film-Noir|Mystery|Thriller                                          3.666667
Comedy|Romance|Sci-Fi                                                            3.666667
Fantasy                                                                          3.666667
Action|Adventure|Children                                                        3.666667
Drama|Mystery|Romance                                                            3.666667
Action|Adventure|Comedy|Fantasy                                                  3.666667
Action|Adventure|Comedy|Fantasy|Sci-Fi                                           3.666667
Adventure|Animation|Children|Fantasy|Musical                                     3.666667
Crime|Drama|Film-Noir                                                            3.666667
Crime|Drama|Film-Noir|Mystery|Thriller                                           3.666667
Action|Adventure|Animation                                                       3.650000
Children|Comedy|Fantasy                                                          3.647059
Comedy|Documentary                                                               3.642857
Comedy|Drama|War                                                                 3.642857
Comedy|Crime|Drama                                                               3.637931
Action|Comedy|Crime                                                              3.628571
Action|Fantasy|Horror                                                            3.625000
Action|Adventure|Comedy|Romance|Thriller                                         3.625000
Comedy|Fantasy|Sci-Fi                                                            3.625000
Action|Animation|Children|Comedy|Sci-Fi|IMAX                                     3.625000
Children|Drama|Mystery                                                           3.625000
Action|Adventure|Crime|Drama|Thriller|War                                        3.625000
Mystery|Sci-Fi|Thriller                                                          3.625000
Action|Crime|Drama|Sci-Fi|Thriller                                               3.625000
Adventure|Animation|Children|Sci-Fi                                              3.625000
Adventure|Animation|Children|Comedy                                              3.614754
Comedy|Drama|Fantasy                                                             3.611111
Western                                                                          3.611111
Drama|Fantasy|Romance                                                            3.607143
Animation|Drama                                                                  3.600000
Adventure|Animation|Children|Comedy|IMAX                                         3.600000
Drama|Mystery                                                                    3.600000
Action|Adventure|Drama|Fantasy                                                   3.595238
Action|Adventure|Thriller|IMAX                                                   3.590909
Action|Adventure|Sci-Fi|Thriller|IMAX                                            3.586207
Animation|Children|Comedy|IMAX                                                   3.583333
Adventure|Animation|Comedy                                                       3.583333
Action|Fantasy|Horror|Thriller                                                   3.571429

In [ ]:
orders_df = pd.read_csv('data/orders.csv', sep=';')
products_df = pd.read_csv('data/products.csv', sep=';')

orders_products = orders_df.merge(
    products_df,
    left_on='ID товара',
    right_on='Product_ID',
    how='left'
)

orders_products[orders_products['Name'].isna()]

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Product_ID,Name,Price,CURRENCY
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103.0,"Носки Подарочные, муж",199.0,RUR
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100,86.0,"Носки Простые, муж",45.0,RUR
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10,104.0,"Носки Подарочные, жен",249.0,RUR
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7,104.0,"Носки Подарочные, жен",249.0,RUR
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5,104.0,"Носки Подарочные, жен",249.0,RUR
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103.0,"Носки Подарочные, муж",199.0,RUR
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1,124.0,Носки беговые Camino,999.0,RUR
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1,91.0,"Носки Честные, муж",50.0,RUR
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3,103.0,"Носки Подарочные, муж",199.0,RUR
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3,104.0,"Носки Подарочные, жен",249.0,RUR
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1,74.0,Платье Ночная Жизнь XXXL,8999.0,RUR
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1,53.0,Штаны Цветочная Поляна,4999.0,RUR
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1,137.0,Гольфы детские Снегурочка,99.0,RUR
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1,47.0,Шатны Полосатый рейс,2999.0,RUR
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1,71.0,Платье Ночная Жизнь,7999.0,RUR
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1,86.0,"Носки Простые, муж",45.0,RUR
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1,51.0,Платье Аленький цветочек,4999.0,RUR
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1,NaN,NaN,NaN,NaN

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Product_ID,Name,Price,CURRENCY
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1,NaN,NaN,NaN,NaN

In [9]:
display(orders_products[orders_products['Статус'] == 'Отменён']['Name'])

6    Носки беговые Camino
Name: Name, dtype: object

In [18]:
orders_products['Profit'] = orders_products['Количество'] * orders_products['Price']
mask = orders_products['Оплачен'] == 'Да'
grouped = orders_products[mask].groupby('ID Покупателя')['Profit'].sum().sort_values(ascending=False)
display(grouped)

ID Покупателя
7    17096.0
5    13043.0
8     1344.0
1        0.0
Name: Profit, dtype: float64